<?php
return [
    'BRANCH_TABLE'=>'CKICO_BRANCH',
    'COMPANY_TABLE'=>'COMPANY',
    'CUSTOMER_TABLE'=>'CUSTOMER',
    'JOB_START_TABLE'=>'JOB_START',//phieu theo doi
    'JOB_D_TABLE'=>'JOB_ORDER_D',//job card
    'JOB_M_TABLE'=>'JOB_ORDER_M',//list chi phi job card
    'MENU_GROUP_TABLE'=>'CKICO_PRO_MENU_GROUP',
    'MENU_TABLE'=>'CKICO_PRO_MENU',
    'PERSONAL_TABLE'=>'PERSONAL',
    'TYPE_COST_TABLE'=>'DM_NOIDUNG',
    'USER_TABLE'=>'USERM',
    'USER_RIGHT_TABLE'=>'USER_RIGHT',
    'PAY_TYPE_TABLE'=>'PAY_TYPE',
    'PAY_NOTE_TABLE'=>'PAY_NOTE',
    'LENDER_TABLE'=>'LENDER',
    'PRO_MENU_TABLE'=>'PRO_MENU',
    'DEBIT_NOTE_D_TABLE'=>'DEBIT_NOTE_D',
    'DEBIT_NOTE_M_TABLE'=>'DEBIT_NOTE_M',
    'BOAT_FEE_M_TABLE'=>'BOAT_FEE_M',
    'BOAT_FEE_D_TABLE'=>'BOAT_FEE_D',
]
?>


